server:
  port: 9999
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Tosucceed

    #change this to your database url
    password: tosucceddev #change this to your database username
    username: root #change this to your database password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
